BEGIN;

ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS signal_timeframe TEXT NOT NULL DEFAULT 'cycle';
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS risk_level TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS active_pairs TEXT[] NOT NULL DEFAULT ARRAY['BTC/USD','ETH/USD','SOL/USD'];
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS stop_loss_percent NUMERIC(5,2) NOT NULL DEFAULT 5.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS take_profit_percent NUMERIC(5,2) NOT NULL DEFAULT 7.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS trailing_stop_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS trailing_stop_percent NUMERIC(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS nonce_error_alerts_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS daily_loss_limit_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS daily_loss_limit_percent NUMERIC(5,2) NOT NULL DEFAULT 10.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS exposure_base TEXT NOT NULL DEFAULT 'cash';
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS position_mode TEXT NOT NULL DEFAULT 'SINGLE';

ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_min_entry_usd NUMERIC(10,2) NOT NULL DEFAULT 100.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_allow_under_min BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_be_at_pct NUMERIC(5,2) NOT NULL DEFAULT 1.50;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_fee_cushion_pct NUMERIC(5,2) NOT NULL DEFAULT 0.45;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_fee_cushion_auto BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_trail_start_pct NUMERIC(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_trail_distance_pct NUMERIC(5,2) NOT NULL DEFAULT 1.50;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_trail_step_pct NUMERIC(5,2) NOT NULL DEFAULT 0.25;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_tp_fixed_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_tp_fixed_pct NUMERIC(5,2) NOT NULL DEFAULT 10.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_scale_out_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_scale_out_pct NUMERIC(5,2) NOT NULL DEFAULT 35.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_min_part_usd NUMERIC(10,2) NOT NULL DEFAULT 50.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_scale_out_threshold NUMERIC(5,2) NOT NULL DEFAULT 80.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_max_open_lots_per_pair INTEGER NOT NULL DEFAULT 1;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS sg_pair_overrides JSONB;

ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS dry_run_mode BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS regime_detection_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS regime_router_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS range_cooldown_minutes INTEGER NOT NULL DEFAULT 60;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS transition_size_factor NUMERIC(4,2) NOT NULL DEFAULT 0.50;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS transition_cooldown_minutes INTEGER NOT NULL DEFAULT 120;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS transition_be_at_pct NUMERIC(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS transition_trail_start_pct NUMERIC(5,2) NOT NULL DEFAULT 2.80;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS transition_tp_pct NUMERIC(5,2) NOT NULL DEFAULT 5.00;

ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS adaptive_exit_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS taker_fee_pct NUMERIC(5,3) NOT NULL DEFAULT 0.400;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS maker_fee_pct NUMERIC(5,3) NOT NULL DEFAULT 0.250;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS profit_buffer_pct NUMERIC(5,2) NOT NULL DEFAULT 1.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS min_be_floor_pct NUMERIC(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS time_stop_hours INTEGER NOT NULL DEFAULT 36;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS time_stop_mode TEXT NOT NULL DEFAULT 'soft';

ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS notif_cooldown_stop_updated INTEGER NOT NULL DEFAULT 60;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS notif_cooldown_regime_change INTEGER NOT NULL DEFAULT 300;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS notif_cooldown_heartbeat INTEGER NOT NULL DEFAULT 3600;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS notif_cooldown_trades INTEGER NOT NULL DEFAULT 0;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS notif_cooldown_errors INTEGER NOT NULL DEFAULT 60;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS error_alert_chat_id TEXT;

-- Spread filter
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_filter_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_dynamic_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_max_pct NUMERIC(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_threshold_trend NUMERIC(5,2) NOT NULL DEFAULT 1.50;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_threshold_range NUMERIC(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_threshold_transition NUMERIC(5,2) NOT NULL DEFAULT 2.50;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_cap_pct NUMERIC(5,2) NOT NULL DEFAULT 3.50;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_floor_pct NUMERIC(5,2) NOT NULL DEFAULT 0.30;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_revolutx_markup_pct NUMERIC(5,2) NOT NULL DEFAULT 0.80;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_telegram_alert_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS spread_telegram_cooldown_ms INTEGER NOT NULL DEFAULT 600000;

-- D2: Dynamic markup from real entry cost history
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS dynamic_markup_enabled BOOLEAN NOT NULL DEFAULT true;
-- MINI-B: Staleness gate
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS staleness_gate_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS staleness_max_sec INTEGER NOT NULL DEFAULT 60;
-- MINI-B: Chase gate
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS chase_gate_enabled BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bot_config ADD COLUMN IF NOT EXISTS chase_max_pct NUMERIC(5,2) NOT NULL DEFAULT 0.50;

COMMIT;
