-- Migration 007: Order Intents for Bot Order Attribution
-- This migration adds the order_intents table and executed_by_bot field to trades
-- to enable proper attribution of trades to bot orders

-- Create order_intents table
CREATE TABLE IF NOT EXISTS order_intents (
  id SERIAL PRIMARY KEY,
  client_order_id TEXT NOT NULL UNIQUE,
  exchange TEXT NOT NULL,
  pair TEXT NOT NULL,
  side TEXT NOT NULL,
  volume DECIMAL(18, 8) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  exchange_order_id TEXT,
  matched_trade_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Add executed_by_bot and order_intent_id to trades table
ALTER TABLE trades ADD COLUMN IF NOT EXISTS executed_by_bot BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS order_intent_id INTEGER;

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_order_intents_exchange_status ON order_intents(exchange, status);
CREATE INDEX IF NOT EXISTS idx_order_intents_client_order_id ON order_intents(client_order_id);
CREATE INDEX IF NOT EXISTS idx_trades_executed_by_bot ON trades(executed_by_bot) WHERE executed_by_bot = TRUE;

-- Comments
COMMENT ON TABLE order_intents IS 'Stores bot order intents for attribution of synced trades';
COMMENT ON COLUMN order_intents.client_order_id IS 'UUID generated by bot before sending order';
COMMENT ON COLUMN order_intents.status IS 'pending, accepted, filled, failed, expired';
COMMENT ON COLUMN trades.executed_by_bot IS 'True if trade was initiated by the bot (matched to order_intent)';
COMMENT ON COLUMN trades.order_intent_id IS 'FK to order_intents.id when trade is matched';
