FROM node:20-alpine

WORKDIR /app

# Git commit passed as build arg (generated by docker-compose or build script)
ARG GIT_COMMIT=unknown

RUN apk add --no-cache libc6-compat docker-cli

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

# Write VERSION file from build arg
RUN echo "${GIT_COMMIT}" > VERSION

RUN npm run build

EXPOSE 5000

ENV NODE_ENV=production
ENV PORT=5000

CMD ["sh", "-c", "npm run db:push && npm start"]
