FROM node:20-alpine

WORKDIR /app

# Git commit passed as build arg (generated by docker-compose or build script)
ARG GIT_COMMIT=unknown

RUN apk add --no-cache libc6-compat docker-cli python3 py3-pip \
  && pip3 install --no-cache-dir scikit-learn numpy joblib --break-system-packages

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

# Write VERSION file from build arg
RUN if [ -s VERSION ] && [ "$(cat VERSION)" != "unknown" ]; then :; else echo "${GIT_COMMIT}" > VERSION; fi

RUN npm run build

EXPOSE 5000

ENV NODE_ENV=production
ENV PORT=5000

CMD ["sh", "-c", "npx tsx script/migrate.ts && npm start"]
