FROM node:20-alpine

WORKDIR /app

# Git commit passed as build arg (generated by docker-compose or build script)
ARG GIT_COMMIT=unknown

RUN apk add --no-cache libc6-compat docker-cli git

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

# Write VERSION file from build arg
RUN if [ "${GIT_COMMIT}" = "unknown" ] && [ -e .git ]; then GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"; fi && echo "${GIT_COMMIT}" > VERSION

RUN npm run build

EXPOSE 5000

ENV NODE_ENV=production
ENV PORT=5000

CMD ["sh", "-c", "npx tsx script/migrate.ts && npm start"]
