/**
 * SpotExecutionAdapter — SHADOW/REAL execution adapters with capability guard.
 *
 * R10: SpotRealAdapter is now FULLY IMPLEMENTED.
 *   - Calls IExchangeService.placeOrder() via ExchangeFactory.getTradingExchange()
 *   - Handles pending fills (order accepted but price not yet known)
 *   - Generates UUID clientOrderId for idempotency
 *   - Records requestedOrderType / effectiveOrderType
 *   - Computes slippage against market context
 *
 * INVARIANT: SHADOW nunca envía órdenes reales. REAL fully functional.
 */

import {
  ExecutionMode,
  REAL_ACTIVATION_ALLOWED,
  type SpotExecutionIntent,
  type SpotExecutionResult,
  type SpotMarketContext,
} from "./spotTypes";
import { getSpotTakerFeePct, getTradingFeeModel, type FeeQuality } from "./feeModel";
import { ExchangeFactory } from "../exchanges/ExchangeFactory";

// ─── Interface ──────────────────────────────────────────────────────────────

export interface SpotExecutionAdapter {
  readonly mode: ExecutionMode;
  readonly canPlaceRealOrder: boolean;

  /**
   * Execute an entry order (BUY).
   * SHADOW: generates phantom fill at current price + controlled slippage.
   * REAL: calls exchange via IExchangeService.placeOrder().
   * clientOrderId is generated by the caller (engine) and passed in — NOT by the adapter.
   */
  executeEntry(intent: SpotExecutionIntent, ctx: SpotMarketContext, clientOrderId: string): Promise<SpotExecutionResult>;

  /**
   * Execute an exit order (SELL).
   * SHADOW: generates phantom fill at current price + controlled slippage.
   * REAL: calls exchange via IExchangeService.placeOrder().
   * clientOrderId is generated by the caller (engine) and passed in — NOT by the adapter.
   */
  executeExit(intent: SpotExecutionIntent, ctx: SpotMarketContext, clientOrderId: string): Promise<SpotExecutionResult>;
}

// ─── Capability guard ───────────────────────────────────────────────────────

export class RealOrderBlockedException extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RealOrderBlockedException";
  }
}

/**
 * Verify that the adapter is allowed to perform the requested operation.
 * Throws if SHADOW tries to place a real order or if REAL is not authorized.
 */
export function assertExecutionCapability(
  adapter: SpotExecutionAdapter,
  intent: SpotExecutionIntent,
): void {
  // SHADOW must never place real orders
  if (adapter.mode === ExecutionMode.SHADOW && !adapter.canPlaceRealOrder) {
    // This is expected — SHADOW generates phantom fills
    return;
  }

  // If somehow SHADOW has canPlaceRealOrder = true, block it
  if (adapter.mode === ExecutionMode.SHADOW && adapter.canPlaceRealOrder) {
    throw new RealOrderBlockedException(
      `SHADOW adapter cannot have canPlaceRealOrder=true. Intent: ${intent.intentId}`,
    );
  }

  // REAL requires explicit activation
  if (adapter.mode === ExecutionMode.REAL && !REAL_ACTIVATION_ALLOWED) {
    throw new RealOrderBlockedException(
      `REAL execution not authorized. REAL_ACTIVATION_ALLOWED=false. Intent: ${intent.intentId}`,
    );
  }

  // REAL adapter must have canPlaceRealOrder = true
  if (adapter.mode === ExecutionMode.REAL && !adapter.canPlaceRealOrder) {
    throw new RealOrderBlockedException(
      `REAL adapter must have canPlaceRealOrder=true. Intent: ${intent.intentId}`,
    );
  }
}

// ─── SHADOW Adapter ─────────────────────────────────────────────────────────

/**
 * Shadow execution adapter.
 * Generates phantom fills with controlled slippage.
 * NEVER calls the exchange API.
 */
export class SpotShadowAdapter implements SpotExecutionAdapter {
  readonly mode = ExecutionMode.SHADOW;
  readonly canPlaceRealOrder = false;

  /**
   * Phantom slippage model:
   *   - Market BUY: pay slightly above ask (slippage = 0.01-0.05%)
   *   - Market SELL: receive slightly below bid (slippage = 0.01-0.05%)
   *   - Slippage is deterministic from intent + ticker (not random)
   */
  private computePhantomSlippagePct(intent: SpotExecutionIntent, ctx: SpotMarketContext): number {
    // Base slippage: 0.02% for market orders
    let slippagePct = 0.02;

    // Higher slippage for larger orders (market impact)
    if (intent.notionalUsd > 1000) slippagePct += 0.01;
    if (intent.notionalUsd > 5000) slippagePct += 0.02;

    // Higher slippage in high volatility
    if (ctx.regimeContext.volatility === "HIGH") slippagePct += 0.02;

    return slippagePct;
  }

  private generatePhantomFill(intent: SpotExecutionIntent, ctx: SpotMarketContext): SpotExecutionResult {
    const ticker = ctx.ticker;
    const slippagePct = this.computePhantomSlippagePct(intent, ctx);
    const slippageMult = slippagePct / 100;

    let fillPrice: number;
    if (intent.side === "BUY") {
      // Buy at ask + slippage
      fillPrice = ticker.ask * (1 + slippageMult);
    } else {
      // Sell at bid - slippage
      fillPrice = ticker.bid * (1 - slippageMult);
    }

    const fillVolume = intent.volume;
    const notional = fillPrice * fillVolume;
    const takerPct = getSpotTakerFeePct() / 100;
    const feeUsd = notional * takerPct;
    const slippageUsd = Math.abs(fillPrice - (intent.side === "BUY" ? ticker.ask : ticker.bid)) * fillVolume;

    const orderId = `shadow-${intent.intentId}-${Date.now().toString(36)}`;

    return {
      success: true,
      orderId,
      clientOrderId: null,
      venueOrderId: null,
      fillPrice,
      fillVolume,
      fillQuality: "ESTIMATED" as FeeQuality,
      feeUsd,
      slippageUsd,
      error: null,
      pendingFill: false,
      executedAt: Date.now(),
    };
  }

  async executeEntry(intent: SpotExecutionIntent, ctx: SpotMarketContext, _clientOrderId: string): Promise<SpotExecutionResult> {
    // Capability guard — verifies SHADOW cannot place real orders
    assertExecutionCapability(this, intent);

    // Verify intent is a BUY
    if (intent.side !== "BUY") {
      return {
        success: false, orderId: null, clientOrderId: null, venueOrderId: null,
        fillPrice: null, fillVolume: null,
        fillQuality: "UNKNOWN" as FeeQuality, feeUsd: null, slippageUsd: null,
        error: "Entry intent must be BUY", pendingFill: false, executedAt: Date.now(),
      };
    }

    // Generate phantom fill (NEVER call exchange)
    return this.generatePhantomFill(intent, ctx);
  }

  async executeExit(intent: SpotExecutionIntent, ctx: SpotMarketContext, _clientOrderId: string): Promise<SpotExecutionResult> {
    // Capability guard
    assertExecutionCapability(this, intent);

    // Verify intent is a SELL
    if (intent.side !== "SELL") {
      return {
        success: false, orderId: null, clientOrderId: null, venueOrderId: null,
        fillPrice: null, fillVolume: null,
        fillQuality: "UNKNOWN" as FeeQuality, feeUsd: null, slippageUsd: null,
        error: "Exit intent must be SELL", pendingFill: false, executedAt: Date.now(),
      };
    }

    // Generate phantom fill (NEVER call exchange)
    return this.generatePhantomFill(intent, ctx);
  }
}

// ─── REAL Adapter (R10: Fully Implemented) ──────────────────────────────────

/**
 * Real execution adapter.
 * R10: Calls the exchange API via IExchangeService.placeOrder().
 * Handles pending fills, UUID clientOrderId, slippage computation.
 */
export class SpotRealAdapter implements SpotExecutionAdapter {
  readonly mode = ExecutionMode.REAL;
  readonly canPlaceRealOrder = true;

  /**
   * Pre-flight validations before sending a real order.
   * Returns an error string if validation fails, null if OK.
   */
  private validateRealIntent(intent: SpotExecutionIntent, ctx: SpotMarketContext): string | null {
    if (!intent.pair) return "Missing pair";
    if (!Number.isFinite(intent.volume) || intent.volume <= 0) return `Invalid volume: ${intent.volume}`;
    if (!ctx.ticker || !Number.isFinite(ctx.ticker.ask) || !Number.isFinite(ctx.ticker.bid)) return "Invalid ticker data";
    if (intent.orderType === "LIMIT" && (intent.price === null || !Number.isFinite(intent.price) || intent.price <= 0)) {
      return `Invalid LIMIT price: ${intent.price}`;
    }
    return null;
  }

  /**
   * Compute slippage: difference between fill price and reference (ask for BUY, bid for SELL).
   */
  private computeSlippage(side: "BUY" | "SELL", fillPrice: number, ctx: SpotMarketContext): number {
    const ref = side === "BUY" ? ctx.ticker.ask : ctx.ticker.bid;
    return Math.abs(fillPrice - ref) * (side === "BUY" ? 1 : 1);
  }

  /**
   * Normalize LIMIT price to the exchange's tick size.
   */
  private normalizeLimitPrice(pair: string, price: number): string {
    const exchange = ExchangeFactory.getTradingExchange();
    const meta = exchange.getPairMetadata(pair);
    if (meta?.priceTickSize && meta.priceTickSize > 0) {
      const tickStr = meta.priceTickSize.toString();
      const tick = parseFloat(tickStr);
      if (Number.isFinite(tick) && tick > 0) {
        return (Math.round(price / tick) * tick).toString();
      }
    }
    return price.toString();
  }

  /**
   * Apply quantity step size to volume.
   */
  private applyQuantityStep(pair: string, volume: number): string {
    const exchange = ExchangeFactory.getTradingExchange();
    const meta = exchange.getPairMetadata(pair);
    if (meta?.quantityStep && meta.quantityStep > 0) {
      const step = parseFloat(meta.quantityStep.toString());
      if (Number.isFinite(step) && step > 0) {
        return (Math.floor(volume / step) * step).toString();
      }
    }
    return volume.toString();
  }

  /**
   * Check order minimum compliance.
   */
  private checkOrderMin(pair: string, volume: number, price: number | null, ctx: SpotMarketContext): string | null {
    const exchange = ExchangeFactory.getTradingExchange();
    const meta = exchange.getPairMetadata(pair);
    // R10.4: FAIL-CLOSED — no metadata = BLOCK, not skip
    if (!meta) return `No pair metadata for ${pair} — cannot validate order minimum (fail-closed)`;
    const orderMin = meta.orderMin ?? meta.minOrderBase;
    if (orderMin && Number.isFinite(orderMin) && orderMin > 0 && volume < orderMin) {
      return `Volume ${volume} below order minimum ${orderMin} for ${pair}`;
    }
    if (meta.minOrderUsd && Number.isFinite(meta.minOrderUsd) && meta.minOrderUsd > 0) {
      const refPrice = price ?? ctx.ticker?.last ?? 0;
      const notional = volume * refPrice;
      if (notional < meta.minOrderUsd) {
        return `Notional ${notional} below min order USD ${meta.minOrderUsd} for ${pair}`;
      }
    }
    return null;
  }

  async executeEntry(intent: SpotExecutionIntent, ctx: SpotMarketContext, clientOrderId: string): Promise<SpotExecutionResult> {
    assertExecutionCapability(this, intent);

    if (intent.side !== "BUY") {
      return this.failResult("Entry intent must be BUY");
    }

    const validationError = this.validateRealIntent(intent, ctx);
    if (validationError) {
      return this.failResult(validationError);
    }

    // clientOrderId is generated by the engine and passed in — NOT by the adapter
    const exchange = ExchangeFactory.getTradingExchange();

    // Apply quantity step
    const volumeStr = this.applyQuantityStep(intent.pair, intent.volume);
    const adjustedVolume = parseFloat(volumeStr);
    if (!Number.isFinite(adjustedVolume) || adjustedVolume <= 0) {
      return this.failResult(`Invalid adjusted volume: ${volumeStr}`);
    }

    // Check order minimum
    const minError = this.checkOrderMin(intent.pair, adjustedVolume, intent.price, ctx);
    if (minError) {
      return this.failResult(minError);
    }

    // Build order params
    const orderParams: any = {
      pair: intent.pair,
      type: "buy" as const,
      ordertype: intent.orderType === "LIMIT" ? "limit" : "market",
      volume: volumeStr,
      clientOrderId,
    };
    if (intent.orderType === "LIMIT" && intent.price !== null) {
      orderParams.price = this.normalizeLimitPrice(intent.pair, intent.price);
    }

    console.log(`[SpotRealAdapter] Entry BUY ${intent.pair} vol=${volumeStr} type=${orderParams.ordertype} clientOrderId=${clientOrderId}`);

    try {
      const result = await exchange.placeOrder(orderParams);

      if (!result.success) {
        return this.failResult(result.error ?? "Exchange rejected order", "REJECTED");
      }

      // Pending fill: order accepted but price unknown
      if (result.pendingFill) {
        console.log(`[SpotRealAdapter] Entry PENDING_FILL orderId=${result.orderId} clientOrderId=${clientOrderId}`);
        return {
          success: true,
          orderId: result.orderId ?? null,
          clientOrderId,
          venueOrderId: result.orderId ?? null,
          fillPrice: null,
          fillVolume: null,
          fillQuality: "UNKNOWN" as FeeQuality,
          feeUsd: null,
          slippageUsd: null,
          error: null,
          pendingFill: true,
          executedAt: Date.now(),
        };
      }

      // Immediate fill
      // R10.4: FAIL-CLOSED — validate fillPrice and fillVolume are finite and positive
      const fillPrice = result.price ?? 0;
      const fillVolume = result.volume ?? adjustedVolume;
      if (!Number.isFinite(fillPrice) || fillPrice <= 0) {
        return this.failResult(`Exchange returned invalid fillPrice=${fillPrice} for ${intent.pair} (fail-closed)`);
      }
      if (!Number.isFinite(fillVolume) || fillVolume <= 0) {
        return this.failResult(`Exchange returned invalid fillVolume=${fillVolume} for ${intent.pair} (fail-closed)`);
      }
      const feeModel = getTradingFeeModel();
      const takerPct = feeModel.takerFeePct / 100;
      const notional = fillPrice * fillVolume;
      const feeUsd = notional * takerPct;
      const slippageUsd = this.computeSlippage("BUY", fillPrice, ctx) * fillVolume;

      console.log(`[SpotRealAdapter] Entry FILLED ${intent.pair} @ ${fillPrice} vol=${fillVolume} fee=$${feeUsd.toFixed(4)}`);

      return {
        success: true,
        orderId: result.orderId ?? null,
        clientOrderId,
        venueOrderId: result.orderId ?? null,
        fillPrice,
        fillVolume,
        fillQuality: feeModel.quality as FeeQuality,
        feeUsd,
        slippageUsd,
        error: null,
        pendingFill: false,
        executedAt: Date.now(),
      };
    } catch (error: any) {
      // R10.4: Network ambiguity — re-throw so caller can mark UNCERTAIN
      if (this.isNetworkError(error)) {
        throw error;
      }
      return this.failResult(`Exchange error: ${error.message}`, "REJECTED");
    }
  }

  async executeExit(intent: SpotExecutionIntent, ctx: SpotMarketContext, clientOrderId: string): Promise<SpotExecutionResult> {
    assertExecutionCapability(this, intent);

    if (intent.side !== "SELL") {
      return this.failResult("Exit intent must be SELL");
    }

    const validationError = this.validateRealIntent(intent, ctx);
    if (validationError) {
      return this.failResult(validationError);
    }

    // clientOrderId is generated by the engine and passed in — NOT by the adapter
    const exchange = ExchangeFactory.getTradingExchange();

    const volumeStr = this.applyQuantityStep(intent.pair, intent.volume);
    const adjustedVolume = parseFloat(volumeStr);
    if (!Number.isFinite(adjustedVolume) || adjustedVolume <= 0) {
      return this.failResult(`Invalid adjusted volume: ${volumeStr}`);
    }

    const orderParams: any = {
      pair: intent.pair,
      type: "sell" as const,
      ordertype: intent.orderType === "LIMIT" ? "limit" : "market",
      volume: volumeStr,
      clientOrderId,
    };
    if (intent.orderType === "LIMIT" && intent.price !== null) {
      orderParams.price = this.normalizeLimitPrice(intent.pair, intent.price);
    }

    console.log(`[SpotRealAdapter] Exit SELL ${intent.pair} vol=${volumeStr} type=${orderParams.ordertype} clientOrderId=${clientOrderId}`);

    try {
      const result = await exchange.placeOrder(orderParams);

      if (!result.success) {
        return this.failResult(result.error ?? "Exchange rejected sell order", "REJECTED");
      }

      // Pending fill for exit
      if (result.pendingFill) {
        console.log(`[SpotRealAdapter] Exit PENDING_FILL orderId=${result.orderId} clientOrderId=${clientOrderId}`);
        return {
          success: true,
          orderId: result.orderId ?? null,
          clientOrderId,
          venueOrderId: result.orderId ?? null,
          fillPrice: null,
          fillVolume: null,
          fillQuality: "UNKNOWN" as FeeQuality,
          feeUsd: null,
          slippageUsd: null,
          error: null,
          pendingFill: true,
          executedAt: Date.now(),
        };
      }

      // Immediate fill
      // R10.4: FAIL-CLOSED — validate fillPrice and fillVolume are finite and positive
      const fillPrice = result.price ?? 0;
      const fillVolume = result.volume ?? adjustedVolume;
      if (!Number.isFinite(fillPrice) || fillPrice <= 0) {
        return this.failResult(`Exchange returned invalid fillPrice=${fillPrice} for ${intent.pair} (fail-closed)`);
      }
      if (!Number.isFinite(fillVolume) || fillVolume <= 0) {
        return this.failResult(`Exchange returned invalid fillVolume=${fillVolume} for ${intent.pair} (fail-closed)`);
      }
      const feeModel = getTradingFeeModel();
      const takerPct = feeModel.takerFeePct / 100;
      const notional = fillPrice * fillVolume;
      const feeUsd = notional * takerPct;
      const slippageUsd = this.computeSlippage("SELL", fillPrice, ctx) * fillVolume;

      console.log(`[SpotRealAdapter] Exit FILLED ${intent.pair} @ ${fillPrice} vol=${fillVolume} fee=$${feeUsd.toFixed(4)}`);

      return {
        success: true,
        orderId: result.orderId ?? null,
        clientOrderId,
        venueOrderId: result.orderId ?? null,
        fillPrice,
        fillVolume,
        fillQuality: feeModel.quality as FeeQuality,
        feeUsd,
        slippageUsd,
        error: null,
        pendingFill: false,
        executedAt: Date.now(),
      };
    } catch (error: any) {
      // R10.4: Network ambiguity — re-throw so caller can mark UNCERTAIN
      if (this.isNetworkError(error)) {
        throw error;
      }
      return this.failResult(`Exchange error: ${error.message}`, "REJECTED");
    }
  }

  /**
   * R10.4: Detect network errors that may indicate the order was placed but
   * the response was lost. These are ambiguous — the order may be live on the exchange.
   */  private isNetworkError(error: any): boolean {
    const msg = (error.message || error.toString()).toLowerCase();
    return msg.includes("timeout")
      || msg.includes("econnreset")
      || msg.includes("econnrefused")
      || msg.includes("etimedout")
      || msg.includes("socket hang up")
      || msg.includes("network")
      || msg.includes("fetch failed")
      || msg.includes("aborted");
  }

  private failResult(error: string, submissionState: "REJECTED" | "AMBIGUOUS" = "REJECTED"): SpotExecutionResult {
    return {
      success: false,
      orderId: null,
      clientOrderId: null,
      venueOrderId: null,
      fillPrice: null,
      fillVolume: null,
      fillQuality: "UNKNOWN" as FeeQuality,
      feeUsd: null,
      slippageUsd: null,
      error,
      pendingFill: false,
      executedAt: Date.now(),
      submissionState,
    };
  }
}

// ─── Adapter factory ────────────────────────────────────────────────────────

/**
 * Factory to create the correct adapter for an execution mode.
 * Fail-safe: unknown mode → SHADOW (never REAL).
 */
export function createExecutionAdapter(mode: ExecutionMode): SpotExecutionAdapter {
  if (mode === ExecutionMode.REAL) {
    return new SpotRealAdapter();
  }
  if (mode === ExecutionMode.SHADOW) {
    return new SpotShadowAdapter();
  }
  // OFF or unknown → SHADOW (fail-safe, never REAL)
  // OFF mode should not call execute at all, but if it does, SHADOW is safe
  return new SpotShadowAdapter();
}
