-- ============================================================
-- IDCA PnL Discrepancy Hotfix - Update Script (OBSOLETO)
-- Cycle #25 (BTC/USD) - Order #764
-- ============================================================
-- ⚠️ ESTE ARCHIVO ES OBSOLETO - NO EJECUTAR
-- ============================================================
-- Este SQL fue un placeholder inicial. La reconciliación real del ciclo #25
-- se aplicó manualmente en staging con un SQL corregido más completo.
--
-- El SQL manual aplicado actualizó:
-- - cycle.total_quantity
-- - cycle.capital_used_usd
-- - cycle.total_cost_basis_usd
-- - cycle.avg_entry_price
-- - cycle.unrealized_pnl_usd
-- - cycle.unrealized_pnl_pct
-- - order.quantity
-- - order.gross_value_usd
-- - order.net_value_usd
-- - order.fees_usd
-- - order.executed_quantity
-- - order.executed_usd
-- - order.avg_fill_price
-- - order.gross_base_qty
-- - order.net_base_qty
-- - order.fee_asset
-- - order.fee_amount
-- - order.fee_source
--
-- Este archivo se mantiene como referencia histórica pero NO debe ejecutarse.
-- ============================================================
